# Generated by Django 5.1.7 on 2025-05-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='is_saved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='playlist_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='playlist_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
